# Generated by Django 4.1 on 2022-08-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_rename_phone_number_registration_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
