# Generated by Django 4.1 on 2022-08-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0004_alter_registration_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='materialprovide',
            field=models.BooleanField(),
        ),
    ]
