# Generated by Django 4.1 on 2022-08-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0005_alter_registration_materialprovide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='materialprovide',
        ),
        migrations.AddField(
            model_name='registration',
            name='creditcard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='debitcard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='passbook',
            field=models.BooleanField(default=True),
        ),
    ]
