# Generated by Django 4.1 on 2022-09-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0006_remove_registration_materialprovide_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='creditcard',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='debitcard',
            field=models.BooleanField(default=True),
        ),
    ]
